using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TranslationSettings {
	public string HowToUse1 = "If you want to play with (a) specific language(s) only, set UseAllLanguages to false and remove all other language codes from the LanguagePool list.";
	public string HowToUse2 = "If UseAllLanguages is set to true, the module will ignore the LanguagePool list and instead pick any language.";
	public string HowToUse3 = "Set LanguagesWithManualOnly to true if you only want the module to select languages that have a dedicated manual available in that language.";
	public bool UseAllLanguages = true;
	public bool UseLanguagesWithManualOnly = false;
	public string[] LanguagePool = {        
		"af",
		"ar",
		"az",
		"be",
		"bg",
		"bn",
		"br",
		"ca",
		"cs",
		"de",
		"el",
		"en",
		"eo",
		"es",
		"eu",
		"fi",
		"fr",
		"fy",
		"gl",
		"he",
		"hi",
		"hr",
		"hu",
		"ga",
		"it",
		"ja",
		"jv",
		"ko",
		"la",
		"lb",
		"mk",
		"ml",
		"nl",
		"oc",
		"pl",
		"pt",
		"ro",
		"ru",
		"so",
		"sv",
		"tl",
		"tr",
		"tt",
		"uk",
		"vi"
	};
	//public string HowToUse4 = "Ignore the settings below. These are automatically generated by the game.";
	//public int ConfigVersion = -1;
}


